version: 2.1

jobs:
  build:
    docker:
      - image: &docker-image cimg/node:12.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test:ci
      - run:
          name: Send coverage to CodeCov
          command: yarn add --dev codecov && ./node_modules/.bin/codecov
      - store_test_results:
          path: test-results

  deploy:
    docker:
      - image: *docker-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Setupe clasprc
          command: echo $CLASPRC_JSON > ~/.clasprc.json
      - run:
          name: Publish changes to Apps Script
          command: yarn push
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
